services:
  - type: web
    name: german-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --app-dir backend"
    healthCheckPath: "/"
    envVars:
      - key: MONGODB_URI
        value: "" # Set your MongoDB connection string (Atlas recommended)
      - key: MONGODB_DB_NAME
        value: "german"
      - key: JWT_SECRET
        value: "change-me" # Override with a strong random secret
      - key: OPENAI_API_KEY
        value: "" # Optional; set to enable AI features
      - key: ENABLE_AI_QUIZ_TOPUP
        value: "false" # Set true only if OPENAI_API_KEY is provided
      - key: ALLOW_SPEECH_FEATURE
        value: "true"
      - key: DEV_MODE
        value: "false"
      - key: ALLOW_DEV_ROUTES
        value: "false"
      - key: FRONTEND_ORIGIN
        value: "" # Set to your Render frontend URL, e.g., https://german-frontend.onrender.com

  - type: web
    name: german-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://german-backend.onrender.com/api/v1" # Update if you rename the backend service

  # --- Staging (optional): enables dev routes and tools ---
  - type: web
    name: german-backend-staging
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --app-dir backend"
    healthCheckPath: "/"
    envVars:
      - key: MONGODB_URI
        value: "" # Staging DB URI
      - key: MONGODB_DB_NAME
        value: "german_staging"
      - key: JWT_SECRET
        value: "change-me-staging"
      - key: OPENAI_API_KEY
        value: "" # Optional
      - key: ENABLE_AI_QUIZ_TOPUP
        value: "false"
      - key: ALLOW_SPEECH_FEATURE
        value: "true"
      - key: DEV_MODE
        value: "true"
      - key: ALLOW_DEV_ROUTES
        value: "true"
      - key: FRONTEND_ORIGIN
        value: "" # Set to staging frontend URL after first deploy

  - type: web
    name: german-frontend-staging
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://german-backend-staging.onrender.com/api/v1"
