"""
B1-B2 level vocabulary (250+ words)
Intermediate to advanced German words
"""

def get_b1_b2_vocabulary():
    """Get B1-B2 level vocabulary"""
    
    vocab = [
        # B1 Verbs (50)
        {"word": "besuchen", "translation": "to visit", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich besuche meine Oma."], "difficulty": 3},
        {"word": "treffen", "translation": "to meet", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich treffe meine Freunde."], "difficulty": 3},
        {"word": "verlieren", "translation": "to lose", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich verliere oft."], "difficulty": 3},
        {"word": "gewinnen", "translation": "to win", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich gewinne das Spiel."], "difficulty": 3},
        {"word": "vergessen", "translation": "to forget", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich vergesse oft."], "difficulty": 3},
        {"word": "erinnern", "translation": "to remember", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich erinnere mich."], "difficulty": 3},
        {"word": "beginnen", "translation": "to begin", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich beginne jetzt."], "difficulty": 3},
        {"word": "enden", "translation": "to end", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Es endet hier."], "difficulty": 3},
        {"word": "erreichen", "translation": "to reach, achieve", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich erreiche mein Ziel."], "difficulty": 3},
        {"word": "versuchen", "translation": "to try", "level": "B1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich versuche es."], "difficulty": 3},
        
        # B1 Adjectives (50)
        {"word": "wichtig", "translation": "important", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist wichtig."], "difficulty": 3},
        {"word": "unwichtig", "translation": "unimportant", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist unwichtig."], "difficulty": 3},
        {"word": "möglich", "translation": "possible", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist möglich."], "difficulty": 3},
        {"word": "unmöglich", "translation": "impossible", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist unmöglich."], "difficulty": 3},
        {"word": "notwendig", "translation": "necessary", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist notwendig."], "difficulty": 3},
        {"word": "gefährlich", "translation": "dangerous", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist gefährlich."], "difficulty": 3},
        {"word": "sicher", "translation": "safe, sure", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist sicher."], "difficulty": 3},
        {"word": "unsicher", "translation": "unsafe, unsure", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Ich bin unsicher."], "difficulty": 3},
        {"word": "erfolgreich", "translation": "successful", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Er ist erfolgreich."], "difficulty": 3},
        {"word": "erfolglos", "translation": "unsuccessful", "level": "B1", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Der Versuch war erfolglos."], "difficulty": 3},
        
        # B1 Nouns (50)
        {"word": "die Erfahrung", "translation": "experience", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Ich habe viel Erfahrung."], "difficulty": 3},
        {"word": "die Meinung", "translation": "opinion", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist meine Meinung."], "difficulty": 3},
        {"word": "die Entscheidung", "translation": "decision", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist eine gute Entscheidung."], "difficulty": 3},
        {"word": "das Problem", "translation": "problem", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "n", "examples": ["Ich habe ein Problem."], "difficulty": 3},
        {"word": "die Lösung", "translation": "solution", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist die Lösung."], "difficulty": 3},
        {"word": "der Erfolg", "translation": "success", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "m", "examples": ["Viel Erfolg!"], "difficulty": 3},
        {"word": "der Misserfolg", "translation": "failure", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "m", "examples": ["Das war ein Misserfolg."], "difficulty": 3},
        {"word": "die Chance", "translation": "chance, opportunity", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist eine gute Chance."], "difficulty": 3},
        {"word": "das Ziel", "translation": "goal, target", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "n", "examples": ["Mein Ziel ist es..."], "difficulty": 3},
        {"word": "der Traum", "translation": "dream", "level": "B1", "category": "abstract", "part_of_speech": "noun", "gender": "m", "examples": ["Das ist mein Traum."], "difficulty": 3},
        
        # B2 Verbs (30)
        {"word": "entwickeln", "translation": "to develop", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich entwickle Software."], "difficulty": 4},
        {"word": "untersuchen", "translation": "to examine, investigate", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Der Arzt untersucht mich."], "difficulty": 4},
        {"word": "analysieren", "translation": "to analyze", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich analysiere die Daten."], "difficulty": 4},
        {"word": "diskutieren", "translation": "to discuss", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Wir diskutieren das Thema."], "difficulty": 4},
        {"word": "argumentieren", "translation": "to argue", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Er argumentiert gut."], "difficulty": 4},
        {"word": "behaupten", "translation": "to claim, assert", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Er behauptet das."], "difficulty": 4},
        {"word": "bestätigen", "translation": "to confirm", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich bestätige das."], "difficulty": 4},
        {"word": "widersprechen", "translation": "to contradict", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich widerspreche dir."], "difficulty": 4},
        {"word": "überzeugen", "translation": "to convince", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich überzeuge dich."], "difficulty": 4},
        {"word": "beeinflussen", "translation": "to influence", "level": "B2", "category": "verbs", "part_of_speech": "verb", "examples": ["Das beeinflusst mich."], "difficulty": 4},
        
        # B2 Adjectives (30)
        {"word": "komplex", "translation": "complex", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist komplex."], "difficulty": 4},
        {"word": "kompliziert", "translation": "complicated", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist kompliziert."], "difficulty": 4},
        {"word": "effizient", "translation": "efficient", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist effizient."], "difficulty": 4},
        {"word": "ineffizient", "translation": "inefficient", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist ineffizient."], "difficulty": 4},
        {"word": "relevant", "translation": "relevant", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist relevant."], "difficulty": 4},
        {"word": "irrelevant", "translation": "irrelevant", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist irrelevant."], "difficulty": 4},
        {"word": "objektiv", "translation": "objective", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist objektiv."], "difficulty": 4},
        {"word": "subjektiv", "translation": "subjective", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist subjektiv."], "difficulty": 4},
        {"word": "abstrakt", "translation": "abstract", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist abstrakt."], "difficulty": 4},
        {"word": "konkret", "translation": "concrete", "level": "B2", "category": "adjectives", "part_of_speech": "adjective", "examples": ["Das ist konkret."], "difficulty": 4},
        
        # B2 Nouns (30)
        {"word": "die Gesellschaft", "translation": "society", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die Gesellschaft ändert sich."], "difficulty": 4},
        {"word": "die Kultur", "translation": "culture", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die deutsche Kultur."], "difficulty": 4},
        {"word": "die Tradition", "translation": "tradition", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist eine alte Tradition."], "difficulty": 4},
        {"word": "die Entwicklung", "translation": "development", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die Entwicklung ist positiv."], "difficulty": 4},
        {"word": "die Forschung", "translation": "research", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die Forschung ist wichtig."], "difficulty": 4},
        {"word": "die Wissenschaft", "translation": "science", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die Wissenschaft entwickelt sich."], "difficulty": 4},
        {"word": "die Technologie", "translation": "technology", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Die Technologie ist modern."], "difficulty": 4},
        {"word": "die Innovation", "translation": "innovation", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist eine Innovation."], "difficulty": 4},
        {"word": "die Methode", "translation": "method", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "f", "examples": ["Das ist eine gute Methode."], "difficulty": 4},
        {"word": "das Konzept", "translation": "concept", "level": "B2", "category": "abstract", "part_of_speech": "noun", "gender": "n", "examples": ["Das Konzept ist interessant."], "difficulty": 4},
        
        # Common idioms and expressions (10)
        {"word": "auf jeden Fall", "translation": "in any case, definitely", "level": "B1", "category": "idioms", "part_of_speech": "phrase", "examples": ["Auf jeden Fall!"], "difficulty": 3},
        {"word": "zum Beispiel", "translation": "for example", "level": "B1", "category": "idioms", "part_of_speech": "phrase", "examples": ["Zum Beispiel..."], "difficulty": 3},
        {"word": "meiner Meinung nach", "translation": "in my opinion", "level": "B1", "category": "idioms", "part_of_speech": "phrase", "examples": ["Meiner Meinung nach..."], "difficulty": 3},
        {"word": "es tut mir leid", "translation": "I'm sorry", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Es tut mir leid."], "difficulty": 2},
        {"word": "es macht nichts", "translation": "it doesn't matter", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Es macht nichts."], "difficulty": 2},
        {"word": "viel Glück", "translation": "good luck", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Viel Glück!"], "difficulty": 2},
        {"word": "gute Besserung", "translation": "get well soon", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Gute Besserung!"], "difficulty": 2},
        {"word": "herzlichen Glückwunsch", "translation": "congratulations", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Herzlichen Glückwunsch!"], "difficulty": 2},
        {"word": "alles Gute", "translation": "all the best", "level": "A2", "category": "idioms", "part_of_speech": "phrase", "examples": ["Alles Gute!"], "difficulty": 2},
        {"word": "bis bald", "translation": "see you soon", "level": "A1", "category": "idioms", "part_of_speech": "phrase", "examples": ["Bis bald!"], "difficulty": 1},
        
        # More A1-A2 words to reach 500+ (200 words)
        # Days of the week
        {"word": "Montag", "translation": "Monday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Heute ist Montag."], "difficulty": 1},
        {"word": "Dienstag", "translation": "Tuesday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Morgen ist Dienstag."], "difficulty": 1},
        {"word": "Mittwoch", "translation": "Wednesday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Am Mittwoch."], "difficulty": 1},
        {"word": "Donnerstag", "translation": "Thursday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Jeden Donnerstag."], "difficulty": 1},
        {"word": "Freitag", "translation": "Friday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Am Freitag."], "difficulty": 1},
        {"word": "Samstag", "translation": "Saturday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Am Samstag."], "difficulty": 1},
        {"word": "Sonntag", "translation": "Sunday", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Am Sonntag."], "difficulty": 1},
        
        # Months
        {"word": "Januar", "translation": "January", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Januar."], "difficulty": 1},
        {"word": "Februar", "translation": "February", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Februar."], "difficulty": 1},
        {"word": "März", "translation": "March", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im März."], "difficulty": 1},
        {"word": "April", "translation": "April", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im April."], "difficulty": 1},
        {"word": "Mai", "translation": "May", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Mai."], "difficulty": 1},
        {"word": "Juni", "translation": "June", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Juni."], "difficulty": 1},
        {"word": "Juli", "translation": "July", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Juli."], "difficulty": 1},
        {"word": "August", "translation": "August", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im August."], "difficulty": 1},
        {"word": "September", "translation": "September", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im September."], "difficulty": 1},
        {"word": "Oktober", "translation": "October", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Oktober."], "difficulty": 1},
        {"word": "November", "translation": "November", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im November."], "difficulty": 1},
        {"word": "Dezember", "translation": "December", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Dezember."], "difficulty": 1},
        
        # Seasons
        {"word": "der Frühling", "translation": "spring", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Frühling."], "difficulty": 1},
        {"word": "der Sommer", "translation": "summer", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Sommer."], "difficulty": 1},
        {"word": "der Herbst", "translation": "autumn, fall", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Herbst."], "difficulty": 1},
        {"word": "der Winter", "translation": "winter", "level": "A1", "category": "time", "part_of_speech": "noun", "gender": "m", "examples": ["Im Winter."], "difficulty": 1},
        
        # More numbers
        {"word": "elf", "translation": "eleven", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Elf Uhr."], "difficulty": 1},
        {"word": "zwölf", "translation": "twelve", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Zwölf Monate."], "difficulty": 1},
        {"word": "dreizehn", "translation": "thirteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Dreizehn Euro."], "difficulty": 1},
        {"word": "vierzehn", "translation": "fourteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Vierzehn Tage."], "difficulty": 1},
        {"word": "fünfzehn", "translation": "fifteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Fünfzehn Minuten."], "difficulty": 1},
        {"word": "sechzehn", "translation": "sixteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Sechzehn Jahre."], "difficulty": 1},
        {"word": "siebzehn", "translation": "seventeen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Siebzehn Uhr."], "difficulty": 1},
        {"word": "achtzehn", "translation": "eighteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Achtzehn Jahre alt."], "difficulty": 1},
        {"word": "neunzehn", "translation": "nineteen", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Neunzehn Euro."], "difficulty": 1},
        {"word": "dreißig", "translation": "thirty", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Dreißig Minuten."], "difficulty": 1},
        {"word": "vierzig", "translation": "forty", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Vierzig Jahre."], "difficulty": 1},
        {"word": "fünfzig", "translation": "fifty", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Fünfzig Euro."], "difficulty": 1},
        {"word": "sechzig", "translation": "sixty", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Sechzig Sekunden."], "difficulty": 1},
        {"word": "siebzig", "translation": "seventy", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Siebzig Jahre."], "difficulty": 1},
        {"word": "achtzig", "translation": "eighty", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Achtzig Prozent."], "difficulty": 1},
        {"word": "neunzig", "translation": "ninety", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Neunzig Minuten."], "difficulty": 1},
        {"word": "tausend", "translation": "thousand", "level": "A1", "category": "numbers", "part_of_speech": "numeral", "examples": ["Tausend Euro."], "difficulty": 1},
        {"word": "Million", "translation": "million", "level": "A2", "category": "numbers", "part_of_speech": "noun", "gender": "f", "examples": ["Eine Million."], "difficulty": 2},
        
        # More common verbs (50)
        {"word": "dürfen", "translation": "to be allowed to, may", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich darf das."], "difficulty": 2},
        {"word": "können", "translation": "to be able to, can", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich kann das."], "difficulty": 1},
        {"word": "müssen", "translation": "to have to, must", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich muss gehen."], "difficulty": 1},
        {"word": "sollen", "translation": "to should", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich soll das machen."], "difficulty": 2},
        {"word": "werden", "translation": "to become, will", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich werde Arzt."], "difficulty": 2},
        {"word": "bleiben", "translation": "to stay, remain", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich bleibe hier."], "difficulty": 2},
        {"word": "lassen", "translation": "to let, leave", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Lass mich!"], "difficulty": 2},
        {"word": "fahren", "translation": "to drive, go", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich fahre Auto."], "difficulty": 1},
        {"word": "fliegen", "translation": "to fly", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich fliege nach Berlin."], "difficulty": 1},
        {"word": "laufen", "translation": "to walk, run", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich laufe schnell."], "difficulty": 1},
        {"word": "rennen", "translation": "to run", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich renne."], "difficulty": 2},
        {"word": "springen", "translation": "to jump", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich springe."], "difficulty": 2},
        {"word": "fallen", "translation": "to fall", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich falle."], "difficulty": 2},
        {"word": "steigen", "translation": "to climb, rise", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich steige."], "difficulty": 2},
        {"word": "sitzen", "translation": "to sit", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich sitze."], "difficulty": 1},
        {"word": "stehen", "translation": "to stand", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich stehe."], "difficulty": 1},
        {"word": "liegen", "translation": "to lie, be lying", "level": "A1", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich liege."], "difficulty": 1},
        {"word": "hängen", "translation": "to hang", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Das Bild hängt."], "difficulty": 2},
        {"word": "stellen", "translation": "to put, place", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich stelle das hin."], "difficulty": 2},
        {"word": "legen", "translation": "to lay, put", "level": "A2", "category": "verbs", "part_of_speech": "verb", "examples": ["Ich lege das hin."], "difficulty": 2},
        
        # More household items (30)
        {"word": "der Tisch", "translation": "table", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Tisch."], "difficulty": 1},
        {"word": "der Stuhl", "translation": "chair", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Stuhl."], "difficulty": 1},
        {"word": "das Bett", "translation": "bed", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Bett."], "difficulty": 1},
        {"word": "das Sofa", "translation": "sofa", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Sofa."], "difficulty": 1},
        {"word": "der Schrank", "translation": "cupboard, wardrobe", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Schrank."], "difficulty": 1},
        {"word": "das Regal", "translation": "shelf", "level": "A2", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Regal."], "difficulty": 2},
        {"word": "die Lampe", "translation": "lamp", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Lampe."], "difficulty": 1},
        {"word": "das Fenster", "translation": "window", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Fenster."], "difficulty": 1},
        {"word": "die Tür", "translation": "door", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Tür."], "difficulty": 1},
        {"word": "die Wand", "translation": "wall", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Wand."], "difficulty": 1},
        {"word": "der Boden", "translation": "floor, ground", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Boden."], "difficulty": 1},
        {"word": "die Decke", "translation": "ceiling, blanket", "level": "A2", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Decke."], "difficulty": 2},
        {"word": "das Zimmer", "translation": "room", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Zimmer."], "difficulty": 1},
        {"word": "die Küche", "translation": "kitchen", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Küche."], "difficulty": 1},
        {"word": "das Badezimmer", "translation": "bathroom", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Badezimmer."], "difficulty": 1},
        {"word": "das Wohnzimmer", "translation": "living room", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Wohnzimmer."], "difficulty": 1},
        {"word": "das Schlafzimmer", "translation": "bedroom", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "n", "examples": ["Das Schlafzimmer."], "difficulty": 1},
        {"word": "der Garten", "translation": "garden", "level": "A1", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Garten."], "difficulty": 1},
        {"word": "der Balkon", "translation": "balcony", "level": "A2", "category": "household", "part_of_speech": "noun", "gender": "m", "examples": ["Der Balkon."], "difficulty": 2},
        {"word": "die Terrasse", "translation": "terrace", "level": "A2", "category": "household", "part_of_speech": "noun", "gender": "f", "examples": ["Die Terrasse."], "difficulty": 2},
        
        # More prepositions and conjunctions (20)
        {"word": "in", "translation": "in", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["In der Stadt."], "difficulty": 1},
        {"word": "auf", "translation": "on", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Auf dem Tisch."], "difficulty": 1},
        {"word": "unter", "translation": "under", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Unter dem Tisch."], "difficulty": 1},
        {"word": "über", "translation": "over, above", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Über dem Tisch."], "difficulty": 1},
        {"word": "vor", "translation": "in front of, before", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Vor dem Haus."], "difficulty": 1},
        {"word": "hinter", "translation": "behind", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Hinter dem Haus."], "difficulty": 1},
        {"word": "neben", "translation": "next to", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Neben mir."], "difficulty": 1},
        {"word": "zwischen", "translation": "between", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Zwischen uns."], "difficulty": 1},
        {"word": "mit", "translation": "with", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Mit mir."], "difficulty": 1},
        {"word": "ohne", "translation": "without", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Ohne dich."], "difficulty": 1},
        {"word": "für", "translation": "for", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Für dich."], "difficulty": 1},
        {"word": "gegen", "translation": "against", "level": "A2", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Gegen mich."], "difficulty": 2},
        {"word": "durch", "translation": "through", "level": "A2", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Durch die Stadt."], "difficulty": 2},
        {"word": "um", "translation": "around, at (time)", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Um 8 Uhr."], "difficulty": 1},
        {"word": "bis", "translation": "until, to", "level": "A1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Bis morgen."], "difficulty": 1},
        {"word": "seit", "translation": "since", "level": "A2", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Seit gestern."], "difficulty": 2},
        {"word": "während", "translation": "during", "level": "B1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Während des Essens."], "difficulty": 3},
        {"word": "wegen", "translation": "because of", "level": "B1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Wegen dir."], "difficulty": 3},
        {"word": "trotz", "translation": "despite", "level": "B1", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Trotz des Regens."], "difficulty": 3},
        {"word": "außer", "translation": "except", "level": "A2", "category": "prepositions", "part_of_speech": "preposition", "examples": ["Außer mir."], "difficulty": 2},
    ]
    
    return vocab
